name=Input Device
version=1.0
author=Tomoji Kanae
maintainer=Tomoji Kanae <https://github.com/Tomoooji>
sentence=Hardware input management library for Arduino and ESP32
paragraph=Support Basic classes and Virtual Input class
category=Device Control
architectures=*